#!/bin/bash

# ------------------------------------------------------------------------------
# GENERAL INFORMATION
# ------------------------------------------------------------------------------
#
# Written by Andrew J Freyer
# GNU General Public License
# http://github.com/andrewjfreyer/monitor
#
# PRINTING AND DEBUGGING
#
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# PRETTY PRINT FOR DEBUG
# ------------------------------------------------------------------------------

# VARIABLES FOR LOGGING LOGSPAM PREVENTION
launch_flag=""

# LOGGING FLAG TO DISTINGUISH SERVICE-LAUNCHED LOGS FROM CONSOLE LOGGED LAUNCHES
$SERVICE_ACTIVE && launch_flag="[+]" || launch_flag="[-]"

# FORK THE LOG FROM THE MAIN THREAD
log_listener () {
    # LOG PIPE
    while true; do
        # SHOULD EXIT?
        [ "$PREF_DISABLE_LOGGING" == true ] && return 0

        # READ FROM THE MAIN PIPE
        local line
        while read line; do
            # ECHO TO CONSOLE, REMOVING EXTRA SPACES
            should_repeat=""
            line_append=""

            if [ "$PREF_REDACT" == true ]; then
                line=$(echo "$line" | sed "s/\([0-9A-Fa-f]\{2\}:\)\{5\}/ [REDACTED]:/gi;s/\([0-9A-Fa-f-]\{36\}\)/ [REDACTED]/gi" )
                line="$line"
            fi

            # ECHO LAST LINE
            echo "$launch_flag $version $(date "+%d-%m-%Y %I:%M:%S %p") $line"
        done < log_pipe
    done
}

# PRINT TO LOG
log() {
    # SEND TO LOG PIPE
    col1=$1
    col2=$2
    [ "$PREF_DISABLE_LOGGING" == false ] && echo "$1    $2" | sed 's/  */ /g' > log_pipe
}
